In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import sys, os
sys.path.append("../../")

In [27]:
import data_loading as dl
import numpy as np
import pandas as pd

df = dl.load_sample(
    "3",
    "runs",
    "mc",
    loadpi0variables=True,
    loadshowervariables=False,
    loadrecoveryvars=False,
    loadsystematics=True,
    enable_cache=False,
    use_bdt=False
)

TypeError: 'Record' object is not iterable

In [15]:
mask = np.array([3,4,5,6]) == 4

In [4]:
df

shr_tkfit_dedx_Y  knobCCMECdn  pi0_dedx1_fit_V  \
0          2.390459e+00          1.0         2.669813   
1         -3.402823e+38          1.0         2.669813   
2         -3.402823e+38          1.0        11.759564   
3         -3.402823e+38          1.0         2.643959   
4          2.084536e+00          1.0         2.629307   
...                 ...          ...              ...   
32181      1.299766e+00          1.0         1.899063   
32182     -3.402823e+38          1.0         3.867588   
32183      3.549811e+00          1.0         3.448260   
32184     -3.402823e+38          1.0         3.448260   
32185      2.052321e+00          1.0         3.405470   

                                                    mc_E  shr1shr2moliereavg  \
0      [1.2899605, 1.5188619, 0.9719122, 1.1050271, 0...        6.033439e+01   
1      [1.5618718, 1.1190978, 1.0742134, 0.9978952, 1...       -3.402823e+38   
2      [0.6346591, 1.0926272, 0.35040653, 0.59712523,...        3.704144e+01   
3                    [0.39379203, 1.3593507, 0.65335846]       -3.402823e+38   
4      [1.1455039, 1.0583467, 0.9701248, 1.0968977, 0...       -3.402823e+38   
...                                                  ...                 ...   
32181                [0.47908616, 1.3355507, 0.16506673]       -3.402823e+38   
32182  [0.28235346, 0.93912387, 1.0108829, 1.0812441,...        3.673277e+01   
32183  [0.4926874, 1.0894089, 0.95407814, 1.0815104, ...        8.647238e+01   
32184       [0.6806253, 1.3753814, 0.6188977, 0.9783396]       -3.402823e+38   
32185       [0.358761, 1.0584656, 1.0040506, 0.16925101]        1.224899e+02   

       slnhits  shr_tkfit_gap10_dedx_Y  tksh_distance  pi0_dir2_x  \
0         5977            2.088274e+00     130.361877   -0.713527   
1         1640           -3.402823e+38      20.722954   -0.122861   
2         1266           -3.402823e+38       4.015627    0.734014   
3         1285           -3.402823e+38     819.205200   -0.489767   
4         1066            2.094036e+00       3.999352    0.000000   
...        ...                     ...            ...         ...   
32181      546            1.025652e+00      98.300056    0.000000   
32182     1274           -3.402823e+38      11.209930    0.087911   
32183     2247            1.927922e+00      39.346123   -0.579459   
32184     1187           -3.402823e+38     494.095184    0.769222   
32185      609            2.139328e+00     338.737122   -0.065325   

       pi0_shrscore1  ...  shr_tkfit_2cm_dedx_Y  shr_theta pi0_energy2_Y  \
0           0.215776  ...          2.692645e+00   1.704218    112.729149   
1           0.006358  ...         -3.402823e+38   0.604006    109.540245   
2           0.061640  ...         -3.402823e+38   0.793823     43.214577   
3           0.003791  ...         -3.402823e+38   0.713942    197.061111   
4          -1.000000  ...          1.999306e+00   1.297637     -1.000000   
...              ...  ...                   ...        ...           ...   
32181      -1.000000  ...          1.573879e+00   1.439713     -1.000000   
32182       0.003597  ...         -3.402823e+38   0.572171    105.331169   
32183       0.357374  ...          3.838962e+00   0.175353     39.339451   
32184       0.000076  ...         -3.402823e+38   0.780036    152.766357   
32185       0.056817  ...          1.977385e+00   0.847886     10.600899   

       reco_nu_vtx_sce_x  knobVecFFCCQEdn  \
0             110.733673              1.0   
1             168.895844              1.0   
2             128.559326              1.0   
3             212.716965              1.0   
4             182.639847              1.0   
...                  ...              ...   
32181          26.532288              1.0   
32182         184.798935              1.0   
32183          90.283974              1.0   
32184         194.517593              1.0   
32185          46.495918              1.0   

                           pfp_generation_v  trk2shrhitdist2 reco_nu_vtx_y  \


In [2]:
import uproot
import pandas as pd

ntuple_path = "/Volumes/LaCie/PELEE_2023_Samples/run3/nuepresel/overlay_peleeTuple_uboone_v08_00_00_70_run3_nu.root"
fold = "nuselection"
tree = "NeutrinoSelectionFilter"
with uproot.open(ntuple_path) as f:
    up = f[fold][tree]
    df = pd.DataFrame(up.arrays(variables, library="np"))


NameError: name 'variables' is not defined

In [15]:
df

shr_tkfit_2cm_nhits_U  pi0truth_gamma2_edep     flash_pe  \
0                          6              0.000000  8025.178711   
1                          0            197.407089  2232.924561   
2                          5              0.000000  3066.440186   
3                          0            282.602203   759.364502   
4                          4             30.054016  1153.027954   
...                      ...                   ...          ...   
32181                      1             65.557320  1975.089722   
32182                      0            156.921890  1552.281860   
32183                      3            193.101212  4260.019043   
32184                      0              0.000000   290.198181   
32185                      3             57.025578  2111.207031   

                                shr_tkfit_dedx_nhits_u_v  trk2shrhitdist2  \
0      [4, 13, 10, 6, 3, 2, 1, -2147483648, 12, 12, -...        33.537083   
1      [-2147483648, 8, 3, 7, 1, -2147483648, -214748...         5.645744   
2         [10, -2147483648, -2147483648, -2147483648, 5]         0.386052   
3                                       [-2147483648, 7]        -1.000000   
4                                             [8, 1, 11]         0.313151   
...                                                  ...              ...   
32181                                          [1, 4, 6]        56.582035   
32182                   [5, -2147483648, 4, -2147483648]        -1.000000   
32183  [-2147483648, 6, -2147483648, 8, -2147483648, ...        39.005692   
32184                                   [-2147483648, 4]        -1.000000   
32185                                [5, 2, -2147483648]        -1.000000   

           nu_e  nproton  pi0truth_gamma1_ypos  pi0truth_gamma_parent  \
0      3.502157        3              0.000000                    111   
1      3.016044        5             -2.546704                    111   
2      2.260406        0              0.000000                      0   
3      1.477599        0            -91.872620                    111   
4      1.881136        1            -15.605298                    111   
...         ...      ...                   ...                    ...   
32181  1.050454        0             58.558174                    111   
32182  0.909001        2             28.566851                    111   
32183  1.774526        1             77.637344                    111   
32184  1.786136        2              0.000000                    111   
32185  0.739763        1             22.262955                    111   

                           pfp_generation_v  ...  isVtxInFiducial  \
0      [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]  ...             True   
1                     [2, 2, 2, 2, 2, 2, 2]  ...             True   
2                           [2, 2, 2, 2, 2]  ...             True   
3                                    [2, 2]  ...            False   
4                                 [2, 2, 2]  ...             True   
...                                     ...  ...              ...   
32181                             [2, 2, 2]  ...             True   
32182                          [2, 2, 2, 2]  ...             True   
32183                    [2, 2, 2, 2, 2, 2]  ...             True   
32184                                [2, 2]  ...            False   
32185                             [2, 2, 2]  ...             True   

      shr_energy_tot  shrclusdir0  \
0           0.553712   248.903809   
1           0.489366    92.542671   
2           0.193148   113.158806   
3           0.427251   175.302109   
4           0.166402   294.541046   
...              ...          ...   
32181       0.079447   183.131409   
32182       0.250112   153.166962   
32183       0.246205    65.316933   
32184       0.409848   247.722290   
32185       0.085259    28.679634   

                                             trk_end_z_v  \
0      [901.7342, 477.87778, 408.43555, 398.35925, 51...   
1     

In [3]:
import data_loading as dl

RUN = ["3"]
all_truth_filters = [
    "nue",
    "dirt",
    # remove the ones below to save some time
    # "nc_pi0",
    # "cc_pi0",
    # "cc_nopi",
    # "cc_cpi",
    # "nc_nopi",
    # "nc_cpi",
]
rundata, mc_weights, data_pot = dl.load_runs(
    RUN,
    data="bnb",
    truth_filtered_sets=all_truth_filters,
    loadpi0variables=True,
    loadshowervariables=True,
    loadrecoveryvars=True,
    loadsystematics=True,
    load_lee=False,
    enable_cache=False,
    cache_dir="cache",
)

/Users/trettin/miniconda/envs/cleanPELEE/lib/python3.12/site-packages/uproot/interpretation/library.py:798: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[name] = series[name]
/Users/trettin/miniconda/envs/cleanPELEE/lib/python3.12/site-packages/uproot/interpretation/library.py:798: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[name] = series[name]
/Users/trettin/miniconda/envs/cleanPELEE/lib/python3.12/site-packages/uproot/interpretation/library.py:798: PerformanceWarning: DataFrame is highly fragmented.  This is usually

KeyboardInterrupt: 

In [2]:
up.show()

name                 | typename                 | interpretation                
---------------------+--------------------------+-------------------------------
selected             | int32_t                  | AsDtype('>i4')
run                  | int32_t                  | AsDtype('>i4')
sub                  | int32_t                  | AsDtype('>i4')
evt                  | int32_t                  | AsDtype('>i4')
trk_id               | uint32_t                 | AsDtype('>u4')
shr_id               | uint32_t                 | AsDtype('>u4')
trk2_id              | uint32_t                 | AsDtype('>u4')
shr2_id              | uint32_t                 | AsDtype('>u4')
trk3_id              | uint32_t                 | AsDtype('>u4')
shr3_id              | uint32_t                 | AsDtype('>u4')
shr_energy_tot       | float                    | AsDtype('>f4')
shr_energy           | float                    | AsDtype('>f4')
shr_energy_second    | float                    | AsDtype(

In [4]:
df = up.arrays(["trk_len", "trkpid", "trk_len_v", "trk_id"], library="pd")
df

trk_len       trkpid  \
0      5.261652e+02     0.991043   
1      2.740138e+01    -0.713021   
2      9.713514e+01     0.115085   
3     -3.402823e+38  9999.000000   
4      1.862045e+01     0.630777   
...             ...          ...   
32181  1.989602e+01     0.005488   
32182  5.305579e+01     0.906225   
32183  1.706434e+02     0.975453   
32184 -3.402823e+38  9999.000000   
32185 -3.402823e+38  9999.000000   

                                               trk_len_v  trk_id  
0      [528.0929565429688, 81.96023559570312, 24.1722...       1  
1      [127.50090026855469, 52.782779693603516, 27.72...       3  
2      [62.800392150878906, 98.4908218383789, 73.4647...       2  
3                  [59.70911407470703, 56.4205436706543]       0  
4      [33.550655364990234, 18.952482223510742, 17.58...       2  
...                                                  ...     ...  
32181  [18.411447525024414, 19.310001373291016, 8.279...       2  
32182  [52.714500427246094, 39.69200134277344, 23.796...       1  
32183  [171.13914489746094, 36.734580993652344, 28.99...       1  
32184            [122.27449035644531, 60.33536148071289]       0  
32185  [15.586389541625977, 3.7304556369781494, 1.348...       0  

[32186 rows x 4 columns]

In [12]:
import awkward as ak

trk_len_v = ak.Array(df["trk_len_v"])
trk_len_v

<Array [[528, 82, 24.2, ..., 10.1, 3.86], ...] type='32186 * var * float64'>

In [14]:
import numpy as np


ids = np.array(df["trk_id"])
trk_len_v[ids]

<Array [[128, 52.8, 27.7, ..., 3.84, 0.898], ...] type='32186 * var * float64'>

In [22]:
len(trk_len_v[0])

12

In [46]:
ids

array([1, 3, 2, ..., 1, 0, 0], dtype=uint32)

In [5]:
from typing import List, Union, Any
import numpy as np
import awkward as ak
from numpy.typing import NDArray

def get_elm_from_vec_idx(
    myvec: ak.Array, idx: Union[List[int], NDArray[Any]], fillval=np.nan
) -> NDArray[np.float64]:
    """Returns the element of a vector at position idx, where idx is a vector of indices. If idx is out of bounds, returns a filler value"""

    return np.array([pidv[tid] if ((tid < len(pidv)) & (tid >= 0)) else fillval for pidv, tid in zip(myvec, idx)])

In [21]:
def get_elm_from_vec_idx_optimized(
    myvec: ak.Array, idx: Union[List[int], np.ndarray], fillval=np.nan
) -> np.ndarray:
    """Returns the element of a vector at position idx, where idx is a vector of indices. 
    If idx is out of bounds, returns a filler value."""

    idx = np.array(idx)
    lengths = ak.num(myvec)
    mask = (idx < lengths) & (idx >= 0)

    # Creating a masked array with valid indices and fillval for invalid ones
    valid_indices = ak.where(mask, idx, 0)
    result = ak.to_numpy(ak.where(mask, myvec[valid_indices], fillval))

    return result

In [22]:
from numpy.testing import assert_array_equal

def test_get_elm_from_vec_idx():
    myvec = ak.Array([[1, 2, 3], [4, 5], [6], [7, 8, 9, 10]])
    idx = [0, 0, 0, 0]
    assert_array_equal(get_elm_from_vec_idx_optimized(myvec, idx), np.array([1, 4, 6, 7]))
    
    idx = [1, 1, 1, 1]
    assert_array_equal(get_elm_from_vec_idx_optimized(myvec, idx), np.array([2, 5, np.nan, 8]))

    idx = [1, 0, 3, 2]
    assert_array_equal(get_elm_from_vec_idx_optimized(myvec, idx), np.array([2, 4, np.nan, 9]))

test_get_elm_from_vec_idx()

TypeError: Conversion of irreducible unions to backend arrays is not supported.

In [71]:
get_elm_from_vec_idx(trk_len_v, ids)

array([ 81.9602356 ,   6.7566905 ,  73.46477509, ...,  36.73458099,
       122.27449036,  15.58638954])

In [51]:
a = ak.Array([[1, 2, 3], [4, 5], [6], [7, 8, 9, 10]])
a

<Array [[1, 2, 3], [4, 5], [6], [7, 8, 9, 10]] type='4 * var * int64'>

In [69]:
idx = [[0], [0], [0], [0]]
a[idx].to_numpy().ravel()

array([1, 4, 6, 7])

In [41]:
idx

array([[0],
       [1],
       [0],
       [2]])